# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=100)),
                ('sex', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=100, null=True)),
                ('statu', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
