# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_types_addtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('pic', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Types')),
            ],
        ),
    ]
