# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='pointnum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
