# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_orderinfo_goodpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='goodid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
