# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_address_addressstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pic',
            field=models.CharField(default='/static/pics/default.jpg', max_length=100, null=True),
        ),
    ]
