# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_auto_20180924_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('create_good', '创建商品'), ('remove_good', '删除商品'), ('remake_good', '更改商品'), ('select_good', '查询商品'))},
        ),
        migrations.AlterModelOptions(
            name='oredr',
            options={'permissions': (('create_order', '创建订单'), ('remove_order', '删除订单'), ('remake_order', '更改订单'), ('select_order', '查询订单'))},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'permissions': (('create_type', '创建商品分类'), ('remove_type', '删除商品分类'), ('remake_type', '更改商品分类'), ('select_type', '查询商品分类'))},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('create_user', '创建用户'), ('remove_user', '删除用户'), ('remake_user', '更改用户'), ('select_user', '查询用户'))},
        ),
    ]
